### PR TITLE
fix: don't ignore dot-directories

### LINKED ISSUE #1223: Nodemon won't restart app
After saving files, nodemon does not restart app, giving the message:
`[nodemon] changes after filters (before/after): 1/0`

Spending several hours I found the solution.
In Windows OS if your have dot in path of your project it displays the message above as soon the dot is removed everything works as expected.

`c:\.projects\your-app` change to `c:\project\your-app` - starts work 👌.

So is it bug or some limitation?

### PR DESCRIPTION
**Pull request by remy**
Fixes #1223

### CODE REVIEW

File: lib/monitor/match.js [hunk 1]
```diff
@@ -167,12 +168,16 @@ function match(files, monitor, ext) {
...
+  debug('rules', rules);
+
   var good = [];
   var whitelist = []; // files that we won't check against the extension
   var ignored = 0;
   var watched = 0;
   var usedRules = [];
-  var minimatchOpts = {};
+  var minimatchOpts = {
+    dot: true,
```
Comment (remy) [inline lib/monitor/match.js]: This is the actual fix.
