### PR TITLE
Find on linux and detect container offset

### LINKED ISSUE #419: no automatic restart when using boot2docker docker volume
nodemon doesn't seem to restart node when using a docker volume, or in this case a boot2docker ( os x -> virtualbox -> docker) volume. nodemon starts okay, but then fails to restart node when a watched file has been modified in the shared OS X volume.

    root@760d5d2ff8cf:/src# nodemon --watch index.js 
    20 Nov 21:06:58 - [nodemon] v1.2.1
    20 Nov 21:06:58 - [nodemon] to restart at any time, enter `rs`
    20 Nov 21:06:58 - [nodemon] watching: index.js
    20 Nov 21:06:58 - [nodemon] starting `nodejs index.js`
    Running on http://localhost:8080
    request received
    #index.js changed and saved here but output does not change as it should
    request received
    request received

`nodemon -L` causes restarts at least once a second even when no files have changed - way too frequently.

`forever -w` seems to work just fine. That seems like the best workaround for now.

output of dump:

    root@b36ab2778133:/src# nodemon --dump
    20 Nov 22:08:27 - [nodemon] v1.2.1
    20 Nov 22:08:27 - [nodemon] to restart at any time, enter `rs`
    20 Nov 22:08:27 - [nodemon] watching: *.*
    --------------
    node: v0.10.25
    nodemon: v1.2.1
    command: node /usr/local/bin/nodemon --dump
    cwd: /src
    OS: linux x64
    --------------
    { run: false,
      system: 
       { cwd: '/src',
         useFind: false,
         useWatch: true,
         useWatchFile: false },
      required: false,
      dirs: [ '/src' ],
      timeout: 1000,
      options: 
       { scriptPosition: 0,
         dump: true,
         script: 'index.js',
         args: [],
         ignore: 
          [ '.git',
            'node_modules',
            'bower_components',
            '.sass-cache',
            re: /\.git|node_modules|bower_components|\.sass\-cache/ ],
         watch: [ '*.*', re: /.*\..*/ ],
         restartable: 'rs',
         execMap: { py: 'python', rb: 'ruby' },
         stdin: true,
         verbose: false,
         stdout: true,
         execOptions: 
          { script: 'index.js',
            exec: 'node',
            args: [],
            nodeArgs: undefined,
            ext: 'js',
            env: {},
            execArgs: [] },
         ext: 'js',
         monitor: 
          [ '*.*',
            '!.git',
            '!/src/node_modules/**/*',
            '!bower_components',
            '!.sass-cache' ] },
      load: [Function],
      reset: [Function: reset],
      lastStarted: 0,
      loaded: [],
      command: 
       { raw: { executable: 'node', args: [ 'index.js' ] },
         string: 'node index.js' } }

### PR DESCRIPTION
**Pull request by remy**
Closes #455
Closes #453
Fixes #419

This method creates a file and checks the stat to check of an offset between the date on the machine and the created time on the file system. Docker (in my tests) show that you can get the offset using this method.

Once we have the offset, we tell the user (once) and then we use that to find files that have been modified according to the offset (either looking in the last using -mmin or in the future using -newer + a touched file).

### CODE REVIEW

File: lib/monitor/watch.js [hunk 1]
```diff
@@ -183,11 +196,11 @@ function ignoredFileTypesForFind(dir) {
     return '';
   }
   var paths = [];
-  if (dir.charAt(dir.length - 1) != '/') {
+  if (dir.charAt(dir.length - 1) !== '/') {
     dir += '/';
   }
   config.options.ignore.forEach(function (path) {
-    var pathIsDir = (fs.existsSync(dir + path) && fs.statSync(dir + path).isDirectory()) || (path.charAt(path.length - 1) == '/');
```
Comment (remy) [inline lib/monitor/watch.js]: These are just jshint fixes.

**Comment by remy** [comment]
Merging because it also fixes the damn `--delay` option.
